language: csharp

matrix:
  include:
    - os: linux
      mono: latest
      dotnet: latest
      script: ./build.sh -t "Travis"
    - os: osx
      mono: latest
      dotnet: latest
      script: ./build.sh -t "Travis"