language: csharp

matrix:
  include:
    - os: linux
      mono: latest
      dotnet:
        - 1.0.4
        - 2.0.0
      script: ./build.sh -t "Travis"
    - os: osx
      mono: latest
      dotnet:
        - 1.0.4
        - 2.0.0
      script: ./build.sh -t "Travis"