version: 1.0.1.{build}
configuration: Release
platform: Any CPU
os: Visual Studio 2017
environment:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_build:
- cmd: dotnet restore
build:
    project: Stranne.VasttrafikNET.sln
    verbosity: quiet
before_test:
- ps: >-
    $nugetPackagePath = $ENV:USERPROFILE + '\.nuget\packages'

    nuget install OpenCover -Version 4.6.703-rc -o $nugetPackagePath
test_script:
- ps: >-
    $resultsFile = $ENV:APPVEYOR_BUILD_FOLDER + '\Stranne.VasttrafikNET_coverage.xml'

    $openCoverConsole = $ENV:USERPROFILE + '\.nuget\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe'

    $target = '-target:C:\Program Files\dotnet\dotnet.exe'
    
    cd "$ENV:APPVEYOR_BUILD_FOLDER\src\Stranne.VasttrafikNET.Tests"

    $targetArgs = '-targetargs: test -c ' + $ENV:CONFIGURATION

    $filter = '-filter:+[Stranne.VasttrafikNET]* -[Stranne.VasttrafikNET.Tests]*'

    $output = '-output:' + $resultsFile

    & $openCoverConsole $target $targetArgs '-register:user' $filter '-hideskipped:Filter' '-returntargetcode' '-mergeoutput' $output '-oldStyle' 
after_test:
- ps: >-
    $ENV:PATH = 'C:\\Python34;C:\\Python34\\Scripts;' + $ENV:PATH
    
    python -m pip install --upgrade pip
    
    pip install git+git://github.com/codecov/codecov-python.git

    codecov -f $resultsFile -X gcov
artifacts:
- path: Stranne.VasttrafikNET_coverage.xml