image:
    - Visual Studio 2022
build_script:
    - ps: dotnet tool restore
    - ps: dotnet cake --target=AppVeyor
test: false
artifacts:
    - path: artifacts\Stranne.VasttrafikNET_coverage.xml
    - path: 'artifacts\**\*.nupkg'
    - path: artifacts\test-report.zip