os: Visual Studio 2017
build_script:
    - ps: .\build.sp1 -Target "AppVeyor"
artifacts:
    - path: artifacts\Stranne.VasttrafikNET_coverage.xml
    - path: artifacts\test-report.zip
    - path: artifacts\*.nupkg'