os: Visual Studio 2017
build_script:
    - ps: .\build.ps1 -target "AppVeyor"
test: off
artifacts:
    - path: artifacts\Stranne.VasttrafikNET_coverage.xml
    - path: 'src\Stranne.VasttrafikNET\**\*.nupkg'
    - path: artifacts\test-report.zip