version: 1.0.1.{build}
configuration: Release
platform: Any CPU
os: Visual Studio 2017
environment:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
cache: 
    - packages -> **\packages.config
before_build:
    - nuget restore
build:
    project: Stranne.VasttrafikNET.sln
    verbosity: normal
after_test:
    - .\packages\OpenCover.4.6.519\OpenCover.Console.exe -register:user -target:xunit.console -targetargs:"/noresults /noisolation /testcontainer:"".\src\Stranne.VasttrafikNET.Tests\bin\$env:CONFIGURATION\netcoreapp1.0\Stranne.VasttrafikNET.Tests.dll" -filter:"+[Stranne.VasttrafikNET]*  -[Stranne.VasttrafikNET.Tests]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\Stranne.VasttrafikNET_coverage.xml
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "Stranne.VasttrafikNET_coverage.xml"