namespace Stranne.VasttrafikNET.Tests.Jsons
{
    public enum JsonFile
    {
        ArrivalBoard,
        AvailableCapacity,
        DefaultToken,
        DepartureBoard,
        ForecastAvailability,
        ForecastFullTime,
        Geometry,
        HistoricalAvailability,
        JourneyDetailError,
        JourneyDetail,
        LiveMap,
        LocationAllStops,
        LocationName,
        LocationNearbyAddress,
        LocationNearbyStops,
        Parking,
        Parkings,
        SystemInfo,
        Trip,
        TrafficSituation,
        TrafficSituations,
        TrafficSituationsJourneies,
        TrafficSituationsLines,
        TrafficSituationsStopAreas,
        TrafficSituationsStopPoints
    }
}
