using System;
using System.Collections.Generic;
using Stranne.VasttrafikNET.ApiModels.TrafficSituations;
using Stranne.VasttrafikNET.ApiModels.TrafficSituations.Enum;
using Stranne.VasttrafikNET.Tests.Jsons;
using Xunit;

namespace Stranne.VasttrafikNET.Tests.JsonParsing
{
    public class TrafficSituationsJsonTest : BaseJsonTest
    {
        public TrafficSituationsJsonTest()
            : base(JsonFile.TrafficSituations)
        { }

        public static TheoryData TestParameters => new TheoryData<string, object>
        {
            { "", 5 },
            { "[0].SituationNumber", "RT1193380" },
            { "[0].CreationTime", new DateTimeOffset(2018, 5, 16, 6, 10, 39, 282, new TimeSpan(2, 0, 0)) },
            { "[0].StartTime", new DateTimeOffset(2018, 4, 30, 16, 6, 0, new TimeSpan(2, 0, 0)) },
            { "[0].EndTime", new DateTimeOffset(2018, 5, 30, 23, 59, 0, new TimeSpan(2, 0, 0)) },
            { "[0].Severity", TrafficSituationSeverity.Severe },
            { "[0].Title", "Linje 82 och 758 stannar inte vid Fältspatsgatan i båda riktningar." },
            { "[0].Description", "Närmaste hållplats är Olof Asklunds gata. Detta gäller från 20 november klockan 09:00 och tillsvidare." },
            { "[0].AffectedStopPoints", 0 },
            { "[0].AffectedLines", 1 },
            { "[0].AffectedLines[0].Gid", "9011014508200000" },
            { "[0].AffectedLines[0].Name", null },
            { "[0].AffectedLines[0].TechnicalNumber", 5082 },
            { "[0].AffectedLines[0].Designation", "82" },
            { "[0].AffectedLines[0].DefaultTransportModeCode", "bus" },
            { "[0].AffectedLines[0].TransportAuthorityCode", "vt" },
            { "[0].AffectedLines[0].TransportAuthorityName", "Västtrafik" },
            { "[0].AffectedLines[0].TextColor", "FFFFFF" },
            { "[0].AffectedLines[0].BackgroundColor", "00A5DC" },
            { "[0].AffectedLines[0].Directions", 2 },
            { "[0].AffectedLines[0].Directions[0].Gid", "9014014508210000" },
            { "[0].AffectedLines[0].Directions[0].DirectionCode", 1 },
            { "[0].AffectedLines[0].Directions[0].Name", "Marklandsgatan - Brottkärr" },
            { "[0].AffectedLines[0].Directions[1].Gid", "9014014508220000" },
            { "[0].AffectedLines[0].Directions[1].DirectionCode", 2 },
            { "[0].AffectedLines[0].Directions[1].Name", "Brottkärr - Marklandsgatan" },
            { "[0].AffectedLines[0].Municipalities", 1 },
            { "[0].AffectedLines[0].Municipalities[0].MunicipalityNumber", 1480 },
            { "[0].AffectedLines[0].Municipalities[0].MunicipalityName", "Göteborg" },
            { "[0].AffectedLines[0].AffectedStopPointGids", 0 },
            { "[0].AffectedJourneys", 0 },

            { "[1].SituationNumber", "RT1270614" },
            { "[1].CreationTime", new DateTimeOffset(2018, 5, 16, 6, 10, 39, 1, new TimeSpan(2, 0, 0)) },
            { "[1].StartTime", new DateTimeOffset(2018, 4, 16, 15, 27, 0, new TimeSpan(2, 0, 0)) },
            { "[1].EndTime", new DateTimeOffset(2018, 12, 8, 22, 00, 0, new TimeSpan(1, 0, 0)) },
            { "[1].Severity", TrafficSituationSeverity.Severe },
            { "[1].Title", "Västtågen Säffle station - Öxnered station, flera inställda avgångar." },
            { "[1].Description", "Bussar ersätter. Detta gäller från 5 mars klockan 04:00 till 8 december klockan 22:00. Information om inställda avgångar och ersättningsbussar finns på vasttrafik.se. Orsaken är banarbete." },
            { "[1].AffectedStopPoints", 10 },
            { "[1].AffectedStopPoints[0].Gid", "9022014016200002" },
            { "[1].AffectedStopPoints[0].Name", "Bohus station" },
            { "[1].AffectedStopPoints[0].ShortName", "Bohus station" },
            { "[1].AffectedStopPoints[0].StopAreaGid", "9021014016200000" },
            { "[1].AffectedStopPoints[0].StopAreaName", "Bohus station" },
            { "[1].AffectedStopPoints[0].StopAreaShortName", "Bohus station" },
            { "[1].AffectedStopPoints[0].MunicipalityName", "Ale" },
            { "[1].AffectedStopPoints[0].MunicipalityNumber", 1440 },
            { "[1].AffectedStopPoints[1].Gid", "9022014016200003" },
            { "[1].AffectedStopPoints[1].Name", "Bohus station" },
            { "[1].AffectedStopPoints[1].ShortName", "Bohus station" },
            { "[1].AffectedStopPoints[1].StopAreaGid", "9021014016200000" },
            { "[1].AffectedStopPoints[1].StopAreaName", "Bohus station" },
            { "[1].AffectedStopPoints[1].StopAreaShortName", "Bohus station" },
            { "[1].AffectedStopPoints[1].MunicipalityName", "Ale" },
            { "[1].AffectedStopPoints[1].MunicipalityNumber", 1440 },
            { "[1].AffectedStopPoints[2].Gid", "9022014002672001" },
            { "[1].AffectedStopPoints[2].Name", "Gamlestaden Station" },
            { "[1].AffectedStopPoints[2].ShortName", "Gamlestaden stn" },
            { "[1].AffectedStopPoints[2].StopAreaGid", "9021014002672000" },
            { "[1].AffectedStopPoints[2].StopAreaName", "Gamlestaden Station" },
            { "[1].AffectedStopPoints[2].StopAreaShortName", "Gamlestaden stn" },
            { "[1].AffectedStopPoints[2].MunicipalityName", "Göteborg" },
            { "[1].AffectedStopPoints[2].MunicipalityNumber", 1480 },
            { "[1].AffectedLines", 0 },
            { "[1].AffectedJourneys", 0 },

            { "[2].SituationNumber", "RT1198789" },
            { "[2].CreationTime", new DateTimeOffset(2018, 5, 16, 6, 10, 39, 142, new TimeSpan(2, 0, 0)) },
            { "[2].StartTime", new DateTimeOffset(2018, 1, 8, 11, 0, 0, new TimeSpan(1, 0, 0)) },
            { "[2].EndTime", new DateTimeOffset(2018, 6, 24, 13, 0, 0, new TimeSpan(2, 0, 0)) },
            { "[2].Severity", TrafficSituationSeverity.Severe },
            { "[2].Title", "Västtågen Laxå - Mariestad, flera inställda avgångar." },
            { "[2].Description", "Bussar ersätter. Detta gäller från 8 januari klockan 11:00 till 24 juni klockan 13:00. Information om inställda avgångar och ersättningsbussar finns på vasttrafik.se. Orsaken är banarbete." },
            { "[2].AffectedStopPoints", 0 },
            { "[2].AffectedLines", 1 },
            { "[2].AffectedLines[0].Gid", "9011014163200000" },
            { "[2].AffectedLines[0].Name", "Västtågen" },
            { "[2].AffectedLines[0].TechnicalNumber", 1632 },
            { "[2].AffectedLines[0].Designation", "TÅG" },
            { "[2].AffectedLines[0].DefaultTransportModeCode", "train" },
            { "[2].AffectedLines[0].TransportAuthorityCode", "vt" },
            { "[2].AffectedLines[0].TransportAuthorityName", "Västtrafik" },
            { "[2].AffectedLines[0].TextColor", "FFFFFF" },
            { "[2].AffectedLines[0].BackgroundColor", "00A5DC" },
            { "[2].AffectedLines[0].Directions", 2 },
            { "[2].AffectedLines[0].Directions[0].Gid", "9014014163210000" },
            { "[2].AffectedLines[0].Directions[0].DirectionCode", 1 },
            { "[2].AffectedLines[0].Directions[0].Name", "Örebro - Lidköping - Göteborg" },
            { "[2].AffectedLines[0].Directions[1].Gid", "9014014163220000" },
            { "[2].AffectedLines[0].Directions[1].DirectionCode", 2 },
            { "[2].AffectedLines[0].Directions[1].Name", "Göteborg - Lidköping - Örebro" },
            { "[2].AffectedLines[0].Municipalities", 12 },
            { "[2].AffectedLines[0].Municipalities[0].MunicipalityNumber", 1489 },
            { "[2].AffectedLines[0].Municipalities[0].MunicipalityName", "Alingsås" },
            { "[2].AffectedLines[0].Municipalities[1].MunicipalityNumber", 1447 },
            { "[2].AffectedLines[0].Municipalities[1].MunicipalityName", "Gullspång" },
            { "[2].AffectedLines[0].Municipalities[2].MunicipalityNumber", 1493 },
            { "[2].AffectedLines[0].Municipalities[2].MunicipalityName", "Mariestad" },
            { "[2].AffectedLines[0].AffectedStopPointGids", 0 },
            { "[2].AffectedJourneys", 0 },

            { "[3].SituationNumber", "RT1273112" },
            { "[3].CreationTime", new DateTimeOffset(2018, 5, 16, 6, 10, 39, 95, new TimeSpan(2, 0, 0)) },
            { "[3].StartTime", new DateTimeOffset(2018, 6, 3, 11, 0, 0, new TimeSpan(2, 0, 0)) },
            { "[3].EndTime", new DateTimeOffset(2018, 6, 3, 12, 0, 0, new TimeSpan(2, 0, 0)) },
            { "[3].Severity", TrafficSituationSeverity.Severe },
            { "[3].Title", "Linje 200 stannar inte vid Bottnaryd industrigatan mot Borås/Jönköping." },
            { "[3].Description", "Närmaste hållplats är Västra Jära och Bottnaryd Nygatan. Detta gäller från 3 juni klockan 11:00 till 3 juni klockan 12:00. Orsaken är ett evenemang." },
            { "[3].AffectedStopPoints", 2 },
            { "[3].AffectedStopPoints[0].Gid", "9022014075204001" },
            { "[3].AffectedStopPoints[0].Name", "Bottnaryd industrigatan" },
            { "[3].AffectedStopPoints[0].ShortName", "industrigatan" },
            { "[3].AffectedStopPoints[0].StopAreaGid", "9021014075204000" },
            { "[3].AffectedStopPoints[0].StopAreaName", "Bottnaryd industrigatan" },
            { "[3].AffectedStopPoints[0].StopAreaShortName", "industrigatan" },
            { "[3].AffectedStopPoints[0].MunicipalityName", "Jönköping" },
            { "[3].AffectedStopPoints[0].MunicipalityNumber", 680 },
            { "[3].AffectedStopPoints[1].Gid", "9022014075204002" },
            { "[3].AffectedStopPoints[1].Name", "Bottnaryd industrigatan" },
            { "[3].AffectedStopPoints[1].ShortName", "industrigatan" },
            { "[3].AffectedStopPoints[1].StopAreaGid", "9021014075204000" },
            { "[3].AffectedStopPoints[1].StopAreaName", "Bottnaryd industrigatan" },
            { "[3].AffectedStopPoints[1].StopAreaShortName", "industrigatan" },
            { "[3].AffectedStopPoints[1].MunicipalityName", "Jönköping" },
            { "[3].AffectedStopPoints[1].MunicipalityNumber", 680 },
            { "[3].AffectedLines", 1 },
            { "[3].AffectedLines[0].Gid", "9011014220000000" },
            { "[3].AffectedLines[0].Name", null },
            { "[3].AffectedLines[0].TechnicalNumber", 2200 },
            { "[3].AffectedLines[0].Designation", "200" },
            { "[3].AffectedLines[0].DefaultTransportModeCode", "bus" },
            { "[3].AffectedLines[0].TransportAuthorityCode", "vt" },
            { "[3].AffectedLines[0].TransportAuthorityName", "Västtrafik" },
            { "[3].AffectedLines[0].TextColor", "FFFFFF" },
            { "[3].AffectedLines[0].BackgroundColor", "00A5DC" },
            { "[3].AffectedLines[0].Directions", 2 },
            { "[3].AffectedLines[0].Directions[0].Gid", "9014014220010000" },
            { "[3].AffectedLines[0].Directions[0].DirectionCode", 1 },
            { "[3].AffectedLines[0].Directions[0].Name", "Borås - Ulricehamn - Jönköping" },
            { "[3].AffectedLines[0].Directions[1].Gid", "9014014220020000" },
            { "[3].AffectedLines[0].Directions[1].DirectionCode", 2 },
            { "[3].AffectedLines[0].Directions[1].Name", "Jönköping - Ulricehamn - Borås" },
            { "[3].AffectedLines[0].Municipalities", 3 },
            { "[3].AffectedLines[0].Municipalities[0].MunicipalityNumber", 680 },
            { "[3].AffectedLines[0].Municipalities[0].MunicipalityName", "Jönköping" },
            { "[3].AffectedLines[0].Municipalities[1].MunicipalityNumber", 1490 },
            { "[3].AffectedLines[0].Municipalities[1].MunicipalityName", "Borås" },
            { "[3].AffectedLines[0].Municipalities[2].MunicipalityNumber", 1491 },
            { "[3].AffectedLines[0].Municipalities[2].MunicipalityName", "Ulricehamn" },
            { "[3].AffectedLines[0].AffectedStopPointGids", 2 },
            { "[3].AffectedLines[0].AffectedStopPointGids[0]", "9022014075204001" },
            { "[3].AffectedLines[0].AffectedStopPointGids[1]", "9022014075204002" },
            { "[3].AffectedJourneys", 0 },

            { "[4].SituationNumber", "RT1173237" },
            { "[4].CreationTime", new DateTimeOffset(2018, 5, 16, 6, 10, 39, 17, new TimeSpan(2, 0, 0)) },
            { "[4].StartTime", new DateTimeOffset(2017, 10, 12, 14, 24, 0, new TimeSpan(2, 0, 0)) },
            { "[4].EndTime", new DateTimeOffset(2018, 8, 31, 16, 0, 0, new TimeSpan(2, 0, 0)) },
            { "[4].Severity", TrafficSituationSeverity.Severe },
            { "[4].Title", "Linje 31 stannar inte vid Högskolan i båda riktningar." },
            { "[4].Description", "Närmaste hållplats är Polishuset. Detta gäller till den 31 augusti klockan 16:00. Orsaken är vägarbete." },
            { "[4].AffectedStopPoints", 0 },
            { "[4].AffectedLines", 1 },
            { "[4].AffectedLines[0].Gid", "9011014203100000" },
            { "[4].AffectedLines[0].Name", null },
            { "[4].AffectedLines[0].TechnicalNumber", 2031 },
            { "[4].AffectedLines[0].Designation", "31" },
            { "[4].AffectedLines[0].DefaultTransportModeCode", "bus" },
            { "[4].AffectedLines[0].TransportAuthorityCode", "vt" },
            { "[4].AffectedLines[0].TransportAuthorityName", "Västtrafik" },
            { "[4].AffectedLines[0].TextColor", "FFFFFF" },
            { "[4].AffectedLines[0].BackgroundColor", "00A5DC" },
            { "[4].AffectedLines[0].Directions", 2 },
            { "[4].AffectedLines[0].Directions[0].Gid", "9014014203110000" },
            { "[4].AffectedLines[0].Directions[0].DirectionCode", 1 },
            { "[4].AffectedLines[0].Directions[0].Name", "Tosseryd - Sjöbo - Centrum" },
            { "[4].AffectedLines[0].Directions[1].Gid", "9014014203120000" },
            { "[4].AffectedLines[0].Directions[1].DirectionCode", 2 },
            { "[4].AffectedLines[0].Directions[1].Name", "Centrum - Sjöbo - Tosseryd" },
            { "[4].AffectedLines[0].Municipalities", 1 },
            { "[4].AffectedLines[0].Municipalities[0].MunicipalityNumber", 1490 },
            { "[4].AffectedLines[0].Municipalities[0].MunicipalityName", "Borås" },
            { "[4].AffectedLines[0].AffectedStopPointGids", 0 },
            { "[4].AffectedJourneys", 0 }
        };

        [Theory, MemberData(nameof(TestParameters))]
        public void TrafficSituationsJsonParsing(string property, object expected)
        {
            TestValue<IEnumerable<TrafficSituationApiModel>>(property, expected);
        }
    }
}
